### ISSUE TITLE
convert map with more then one key to binary

### ISSUE THREAD

**Issue by AlexeyAlexey** [potatosalad/ruby-erlang-etf#4]
Hello,

   How can I convert map with more then one key?
  If I convert map with more then one key to binary and then convert binary to map from elixir console I get above result. 

Rails console

    2.2.4 :185 >   term = Erlang::Map[:data, "key must be :data", :signed, "key must be :signed"]
     => #<Erlang::Map #{:data=>"key must be :data", :signed=>"key must be :signed"}> 
    2.2.4 :186 > Erlang.term_to_binary(term)
     => "\x83t\x00\x00\x00\x02s\x04datas\x06signedm\x00\x00\x00\x11key must be   :datam\x00\x00\x00\x13key must be :signed" 

Elixir console

    iex(75)> :erlang.binary_to_term("\x83t\x00\x00\x00\x02s\x04datas\x06signedm\x00\x00\x00\x11key   must be :datam\x00\x00\x00\x13key must be :signed")                          
    %{:data => :signed, "key must be :data" => "key must be :signed"}

:data must have  "key must be :data" value but has :signed

:signed  must be as key of map and must have "key must be :signed" value

**Comment by potatosalad** [comment]
Hey @AlexeyAlexey,

I just commented about this on #5, but this should be fixed in [version 2.0.0 of erlang-etf](https://rubygems.org/gems/erlang-etf/versions/2.0.0).
